update reqs? getting weird error (#73)
    sanic.exceptions.SanicException: Sanic app name 'ntserv' not found.
    App instantiation must occur outside if __name__ == '__main__' block or by using an AppLoader.

fix Sanic AppLoader, rm main, track .env not .env.creds

    still getting this error, but it's in better shape:

    sanic.exceptions.ServerError:
        Duplicate route names detected: ntserv._.

fix Sanic unique route names

fix tests (need to investigate rounding error)

new syntax in systemd service (sanic CLI vs. launching from our code)

source .env first (in GitHub integration test workflow)